### ISSUE TITLE
The cooldown for obtaining missiles significantly shortens after dying.

### ISSUE THREAD

**Issue by Wind0220** [Butzlabben/missilewars#102]
**Describe the bug**
When playing the missile war game, there is an issue with the missile cooldown after respawning. The cooldown time for obtaining a missile is significantly reduced compared to the normal cooldown time.

**To Reproduce**

1. Go to the missile war game.
2. Allow the missile to go on its normal cooldown timer.
3. Quickly get defeated or die in the game.
4. Respawn or revive in the game.
5. Try to obtain another missile.

**Expected behavior**
The expected behavior is that the missile cooldown timer should remain consistent and not be affected by the player's death or respawn. It should maintain the regular cooldown time, even after the player dies and respawns.

**Screenshots**

https://github.com/daniel-naegele/missilewars/assets/96609471/e0bb6e3e-1462-40a2-b8fd-c23ec91e75c5

**Server (please complete the following information):**

- OS: [Debian]
- Minecraft version [1.20.1]
- Java version [17]
- Version [v4.5.3]

**Additional context**

**Comment by RedstoneFuture** [comment]
I will see that the behavior is changeable in the config. The item respawn delay is quite important for the game flow.

Thanks for the report.

**Comment by RedstoneFuture** [comment]
@daniel-naegele One possible arena configuration solution looks like this:

Old:
```
equipment_interval:
  start: 10
  intervals_by_team_amount:
  [...]
  interval_factor_by_game_time:
  [...]
```

New:
```
equipment_interval:
  # start intervall for game start and respawn
  custom_start_interval:
    enable: false
    interval: 10
  intervals_by_team_amount:
  [...]
  interval_factor_by_game_time:
  [...]
```

**Comment by Wind0220** [comment]
Thank you very much for your response,I will now proceed to try the new config.

**Comment by RedstoneFuture** [comment]
> Thank you very much for your response,I will now proceed to try the new config.

That was a config concept for development planning.
We will write you here when it is implemented, and then we will close the issue.

**Comment by RedstoneFuture** [comment]
The settings will be included in the next version. The description in the wiki has also been updated.

```
equipment_interval:
  custom_start_interval: 10
  reset_after_respawn: false
  custom_respawn_interval: -1
  intervals_by_team_amount:
  [...]
  interval_factor_by_game_time:
  [...]
```
