### ISSUE TITLE
the spawnpoint lobby does not differentiate the world

### ISSUE THREAD

**Issue by 100petr** [Butzlabben/missilewars#103]
**Describe the bug**
> A clear and concise description of what the bug is.

If I use the command /mw setup lobby spawnpoint to set the spawnpoint for the lobby, it doesn't differentiate the worlds. So if I set it in world1 and the main world is world, it ports me to world.

**To Reproduce**

1. Create a new world via multiverse-core
2. Create a spawnpoint lobby in the new world
3. Create a missilewars sign
4. Try where it teleports you

**Expected behavior**
> A clear and concise description of what you expected to happen.

The name of the world in which the spawnponint is is written into the file. So the function will teleport correctly. 

**Screenshots**
> If applicable, add screenshots to help explain your problem.

![image](https://github.com/daniel-naegele/missilewars/assets/29830635/e8e89bd8-1aa4-4c83-afa2-19de8ab9c70f)

**Server (please complete the following information):**

- OS: [e.g. Debian, Windows]
- Minecraft version 1.20.1
- Java version [e.g. 11, 17]
- Version 4.5.3

**Additional context**
> Add any other context about the problem here.

**Comment by RedstoneFuture** [comment]
Yes, that's right. Currently, we have for a "lobby" the configurable points "spawn_point", "after_game_spawn" and "arena: Pos1" + "arena: Pos2". For everything, however, the world "world" is currently taken in the lobby config, so that we always talk about the same world.

We would have to change a little more to fix that.

```
---
[...]
world: "world"
[...]
spawn_point:
  x: 176.0
  "y": 73.0
  z: -384.0
  yaw: 0.0
  pitch: 0.0
after_game_spawn:
  x: 176.0
  "y": 73.0
  z: -384.0
  yaw: 0.0
  pitch: 0.0
area:
  min_x: 146
  min_y: 0
  min_z: -414
  max_x: 206
  max_y: 256
  max_z: -354
[...]
```
