### ISSUE TITLE
Feature request: Add .schem schematic support

### ISSUE THREAD

**Issue by pjindras** [Butzlabben/missilewars#125]
FAWE schematics are saved as .schem files, 

I reworked the rockets with noteblocks to keep it working, but I found this "issue".

**Comment by RedstoneFuture** [comment]
Both should already be working.

https://github.com/RedstoneFuture/missilewars/blob/68c2c7ccb8f3edb33a1b2b139439aab79edb897a/missilewars-plugin/src/main/java/de/butzlabben/missilewars/game/schematics/objects/SchematicObject.java#L33-L34

".schematic" should still be usable in WorldEdit and FAWE.

**Comment by pjindras** [comment]
I tried .schem schematics, but they werent working, I had to convert them using https://puregero.github.io/SchemToSchematic/, .schem missiles werent found in the file

**Comment by RedstoneFuture** [comment]
Have you tested it with WE or FAWE? I know that it works with FAWE.

**Comment by RedstoneFuture** [comment]
FAWE can paste a `.schematic` correctly.

![grafik](https://github.com/RedstoneFuture/missilewars/assets/4140635/63278dd5-48dd-49a6-9cc3-48180a80e559)


Und MissileWars support both file formats too:

![grafik](https://github.com/RedstoneFuture/missilewars/assets/4140635/51648ea9-9234-4303-8b67-1b2dacc293e5)
```
  schematics:
   # A:
  - egg: "BLAZE"
    down: 2
    dist: 2
    schematic: "Cruiser.schem"
    name: "&eCruiser (.schem)"
    occurrence: 2
   # B:
  - egg: "BLAZE"
    down: 2
    dist: 2
    schematic: "Cruiser.schematic"
    name: "&eCruiser (.schematic)"
    occurrence: 2
```
