### ISSUE TITLE
Feature request: Improve reward system

### ISSUE THREAD

**Issue by pjindras** [Butzlabben/missilewars#126]
It would be very nice if it was possible to make a command as a reward or specify the reward better than only money.

**Comment by RedstoneFuture** [comment]
At the end of the game if you have won or also for other cases?

**Comment by pjindras** [comment]
at the end of the game it would be nice, if the player could get some reward by console command

**Comment by RedstoneFuture** [comment]
Do we need any placeholders other than UUID and player name for the commands?

**Comment by pjindras** [comment]
I think we just need the player's name

**Comment by RedstoneFuture** [comment]
**Configuration concept (planned):**

- supports [Action Types](https://github.com/RedstoneFuture/missilewars/wiki/Menus#action-types)
- supports PAPI
- supports `%player_uuid%` and `%player_name%` placeholder

Part of `<arena>.yml`:
```yml
end_game_action:
  player:
    win:
    - "[console-cmd] eco give %player_name% 80"
    loss:
    - "[console-cmd] eco give %player_name% 10"
    draw:
    - "[console-cmd] eco give %player_name% 40"
  spectator: []
```
