### ISSUE TITLE
Possible wrong defaults in arena configuration

### ISSUE THREAD

**Issue by 100petr** [Butzlabben/missilewars#89]
**Describe the bug**

You can't move in the arena, when you try to move it spams the chat "You are not allowed to leave the arena".

**To Reproduce**
Start the server with the plugin (tested on latest version - 4.5.2)
Wait for the game to start
Once you're in the arena, try to move

**Expected behavior**

It won't spam me in chat and I'll be able to move

**Screenshots**

**Server (please complete the following information):**
Purpur 1.19.4

**Additional context**

Version 4.4.2 does not have this problem

**Comment by daniel-naegele** [comment]
Can you provide me your arena.yaml configuration? On the first look I would guess this is a configuration mistake. Check your X, Y, Z coordinates in the config.

**Comment by 100petr** [comment]
The coordinates should be correct. I'm in Team1. 
```
area:
  min_x: -30
  min_y: 0
  min_z: -72
  max_x: 30
  max_y: 0
  max_z: 72
team1_spawn:
  x: 0.5
  "y": 100.0
  z: 45.5
  yaw: 180.0
  pitch: 0.0
```
![image](https://github.com/daniel-naegele/missilewars/assets/29830635/bff6b638-0d7e-48e5-8d91-2e8b998e9154)

**Comment by daniel-naegele** [comment]
The coordinates are, in fact, not correct. Your max_y coordinate is set to 0, which means, that the area is a flat/has no volume. Set it to for example 150

**Comment by 100petr** [comment]
Then there must be an error in the default settings. I didn't touch the coordinates.

**Comment by daniel-naegele** [comment]
@RedstoneFuture maybe this is worth a look

**Comment by RedstoneFuture** [comment]
Arena configuration with new generated config (newest local version):

```
area:
  min_x: -30
  min_y: 0
  min_z: -72
  max_x: 30
  max_y: 256
  max_z: 72
```

So the default config `arenas\arena0.yml` looks correct here.
